name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload HTML file
      uses: actions/upload-artifact@v3
      with:
        name: html-file
        path: hello.html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download HTML file
      uses: actions/download-artifact@v3
      with:
        name: html-file

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
