name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        name: html-artifact
        path: 'hello.html'
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
